# -*- coding: utf-8 -*-
{
    'name': 'various customizations',
    'category': 'customizations',
    'description': "Add the fields in various models and reports",
    'author': 'Odoo PSIN',
    'odoo_task_id': '3740936',
    'depends': [
        'account',
        'mrp',
        'sale_management',
        'stock',
        'purchase',
        'quality_control',
        'purchase_request',
        'approvals',
        'stock_enterprise',
        'merge_rfq',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/product_reference_sequence.xml',
        'data/stock_picking_grn_sequence.xml',
        'views/account_move_views.xml',
        'views/report_invoice.xml',
        'views/mrp_views.xml',
        'report/mrp_produciton_templates.xml',
        'views/sale_order_views.xml',
        'report/sale_templates.xml',
        'views/stock_picking_views.xml',
        'report/stock_picking_templates.xml',
        'report/purchase_order_templates.xml',
        'views/product_category_views.xml',
        'views/res_partner_views.xml',
        'views/quality_control_view.xml',
        'views/purchase_views.xml',
        'views/defect_entry_views.xml',
        'views/purchase_request_view.xml',
        'wizard/stock_backorder_confirmation_views.xml',
        'wizard/open_purchase_order_summary_report_views.xml',
        'views/product_attribute_views.xml',
        'views/report_access.xml',
        'data/purchase_request_sequence.xml',
        'wizard/purchase_request_line_make_purchase_order_view.xml',
        'wizard/grn_picking_report_views.xml',
        'wizard/spend_analysis_view.xml',

    ],
    'application': False,
    'installable': True,
    'license': 'LGPL-3',
}
