# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError

from collections import defaultdict
import pdb
from num2words import num2words


class AccountRegisterPayments(models.TransientModel):
    _inherit = "account.payment.register"

    bank_reference = fields.Char(copy=False)
    cheque_reference = fields.Char(copy=False)
    effective_date = fields.Date('Effective Date',
                                 help='Effective date of PDC', copy=False,
                                 default=False)
    check_amount_in_words = fields.Char(string="Amount in Words",
                                        help="Total amount in words is automatically generated by the system",
                                        compute='_compute_amount2words')
    pdc_type = fields.Selection(
        [("incoming_pdc", "Customer"), ("outgoing_pdc", "Supplier")])
    payment_method_line_id = fields.Many2one('account.payment.method.line', string='Payment Method')
    is_pdc = fields.Boolean(string='IS PDC', compute='get_pdc')
    invoice_reference = fields.Char(string='Invoice Reference')

    @api.onchange('payment_method_line_id')
    @api.depends('payment_method_line_id')
    def get_pdc(self):
        for record in self:
            if record.payment_method_line_id.name == 'PDC':
                record.is_pdc = True
            else:
                record.is_pdc = False

    @api.depends('amount')
    def _compute_amount2words(self):
        for rec in self:
            if rec.amount:
                rec.check_amount_in_words = str.title(num2words(rec.amount)) + ' ' + rec.currency_id.name

    @api.onchange('partner_type')
    def _partner_type_pdc(self):
        if self.partner_type == 'customer':
            self.pdc_type = 'incoming_pdc'
        elif self.partner_type == 'supplier':
            self.pdc_type = 'outgoing_pdc'

    def post_sales(self):
        self.env['account.move'].with_context(default_type='entry')
        for rec in self:

            if rec.state != 'draft':
                raise UserError(_("Only a draft payment can be posted."))

            if any(inv.state != 'posted' for inv in rec.invoice_ids):
                raise ValidationError(_("The payment cannot be processed because the invoice is not open!"))

            # keep the name in case of a payment reset to draft
            if not rec.name:
                # Use the right sequence to set the name
                if rec.payment_type == 'transfer':
                    sequence_code = 'account.payment.transfer'
                else:
                    if rec.partner_type == 'customer':
                        if rec.payment_type == 'inbound':
                            sequence_code = 'account.payment.customer.invoice'
                        if rec.payment_type == 'outbound':
                            sequence_code = 'account.payment.customer.refund'
                    if rec.partner_type == 'supplier':
                        if rec.payment_type == 'inbound':
                            sequence_code = 'account.payment.supplier.refund'
                        if rec.payment_type == 'outbound':
                            sequence_code = 'account.payment.supplier.invoice'
                rec.name = self.env['ir.sequence'].next_by_code(sequence_code, sequence_date=rec.payment_date)
                if not rec.name and rec.payment_type != 'transfer':
                    raise UserError(_("You have to define a sequence for %s in your company.") % (sequence_code,))
        return True

    def create_draft_pdc_payment(self):
        account_move_id = self._context.get('active_ids')[0]
        active_id = self.env['account.move'].search([('id', '=', account_move_id)])
        pdc_draft_payment = self.env["account.payment"]
        for value in self:
            if value.pdc_type:
                if value.pdc_type == 'incoming_pdc':
                    if value.amount > 0.00:
                        rec = pdc_draft_payment.sudo().create(
                            {
                                "payment_type": 'inbound',
                                "partner_id": value.partner_id.id,
                                "amount": value.amount,
                                "journal_id": value.journal_id.id,
                                "ref": value.communication,
                                "invoice_reference": value.invoice_reference,
                                "payment_method_line_id": value.payment_method_line_id.id,
                                "bank_reference": value.bank_reference,
                                "cheque_reference": value.cheque_reference,
                                "date": fields.Datetime.now(),
                                "effective_date": value.effective_date,
                            }
                        )
                        rec.action_post()
                    else:
                        raise ValidationError(
                            _('Alert !!  Mr.%s - You cannot create PDC Draft Payment with Zero Value '
                              'Please Check it.') % value.env.user.name)
                if value.pdc_type == 'outgoing_pdc':
                    if value.amount > 0.00:
                        rec = pdc_draft_payment.sudo().create(
                            {
                                "payment_type": 'outbound',
                                "partner_id": value.partner_id.id,
                                "amount": value.amount,
                                "journal_id": value.journal_id.id,
                                "ref": value.communication,
                                "invoice_reference": value.invoice_reference,
                                "payment_method_line_id": value.payment_method_line_id.id,
                                "bank_reference": value.bank_reference,
                                "cheque_reference": value.cheque_reference,
                                "date": fields.Datetime.now(),
                                "effective_date": value.effective_date,
                            }
                        )
                        rec.action_post()
                    else:
                        raise ValidationError(
                            _('Alert !!  Mr.%s - You cannot create PDC Draft Payment with Zero Value '
                              'Please Check it.') % value.env.user.name)
            else:
                raise ValidationError(
                    _('Alert !!  Mr.%s - You cannot create PDC Draft Payment without Selecting the PDC Type.'
                      '\n Please Select and Proceed Further.') % value.env.user.name)
        active_id.write({
            'pdc_bool': True
        })

    def _prepare_payment_vals(self, invoices):
        res = super(AccountRegisterPayments, self)._prepare_payment_vals(invoices)
        # Check payment method is Check or PDC
        check_pdc_ids = self.env['account.payment.method'].search(
            [('code', 'in', ['pdc', 'check_printing'])])
        if self.payment_method_id.id in check_pdc_ids.ids:
            currency_id = self.env['res.currency'].browse(res['currency_id'])
            journal_id = self.env['account.journal'].browse(res['journal_id'])
            # Updating values in case of Multi payments
            res.update({
                'bank_reference': self.bank_reference,
                'cheque_reference': self.cheque_reference,
                'check_manual_sequencing': journal_id.check_manual_sequencing,
                'effective_date': self.effective_date,
                'check_amount_in_words': currency_id.amount_to_text(
                    res['amount']),
            })
        return res


class AccountPayment(models.Model):
    _inherit = "account.payment"

    pdc_cheque_id = fields.Many2one('post.dated.cheques', string='PDC Cheque',
                                    tracking=True, readonly=True)
    active = fields.Boolean('Active', default=True)

    def post(self):
        res = super(AccountPayment, self).post()
        if self.payment_method_id.code == 'pdc':
            if not self.pdc_cheque_id:
                pdc_payment = self.env['post.dated.cheques'].create({
                    # 'name': self.name,
                    'partner_type': self.partner_type,
                    'payment_reference': self.payment_reference,
                    'journal_id': self.journal_id.id,
                    'payment_type': self.payment_type,
                    'partner_id': self.partner_id.id,
                    'amount': self.amount,
                    'currency_id': self.currency_id.id,
                    'bank_reference': self.bank_reference,
                    'cheque_reference': self.cheque_reference,
                    'effective_date': self.effective_date,
                    'communication': self.communication,
                    'invoice_reference': self.invoice_reference,
                    'payment_date': self.payment_date,
                    'payment_id': self.id,
                    'company_id': self.company_id.id,
                    'state': 'registered',
                })
                self.write({'pdc_cheque_id': pdc_payment.id})
            if self.pdc_cheque_id:
                self.pdc_cheque_id.write({
                    'partner_type': self.partner_type,
                    'payment_reference': self.payment_reference,
                    'journal_id': self.journal_id.id,
                    'payment_type': self.payment_type,
                    'partner_id': self.partner_id.id,
                    'amount': self.amount,
                    'currency_id': self.currency_id.id,
                    'bank_reference': self.bank_reference,
                    'cheque_reference': self.cheque_reference,
                    'effective_date': self.effective_date,
                    'communication': self.communication,
                    'invoice_reference': self.invoice_reference,
                    'payment_date': self.payment_date,
                    'payment_id': self.id,
                    'company_id': self.company_id.id,
                    'state': 'registered',
                })
        return res

    bank_reference = fields.Char(copy=False)
    cheque_reference = fields.Char(copy=False)
    effective_date = fields.Date('Effective Date',
                                 help='Effective date of PDC', copy=False,
                                 default=False)
    payment_method_line_id = fields.Many2one('account.payment.method.line', string='Payment Method')

    def open_payment_matching_screen(self):
        # Open reconciliation view for customers/suppliers
        move_line_id = False
        for move_line in self.line_ids:
            if move_line.account_id.reconcile:
                move_line_id = move_line.id
                break
        if not self.partner_id:
            raise UserError(_("Payments without a customer can't be matched"))
        action_context = {'company_ids': [self.company_id.id], 'partner_ids': [
            self.partner_id.commercial_partner_id.id]}
        if self.partner_type == 'customer':
            action_context.update({'mode': 'customers'})
        elif self.partner_type == 'supplier':
            action_context.update({'mode': 'suppliers'})
        if move_line_id:
            action_context.update({'move_line_id': move_line_id})
        return {
            'type': 'ir.actions.client',
            'tag': 'manual_reconciliation_view',
            'context': action_context,
        }

    def create_pdc_check_payment_status(self):
        for rec in self:
            if rec.payment_type == 'inbound' and rec.payment_method_line_id.name == 'PDC':
                # pdb.set_trace()
                pdc_payment = self.env['post.dated.cheques'].sudo().create({
                    # 'name': self.name,
                    'partner_type': 'customer',
                    'payment_reference': rec.payment_reference,
                    'journal_id': rec.journal_id.id,
                    'payment_type': rec.payment_type,
                    'partner_id': rec.partner_id.id,
                    'amount': rec.amount,
                    'currency_id': rec.currency_id.id,
                    'bank_reference': rec.bank_reference,
                    'cheque_reference': rec.cheque_reference,
                    'effective_date': rec.effective_date,
                    'communication': rec.ref,
                    'invoice_reference': rec.invoice_reference,
                    'payment_date': rec.date,
                    'payment_id': rec.id,
                    'company_id': rec.company_id.id,
                    'check_amount_in_words': rec.check_amount_in_words,
                    'state': 'registered',
                })
            if rec.payment_type == 'outbound' and rec.payment_method_line_id.name == 'PDC':
                pdc_payment = self.env['post.dated.cheques'].sudo().create({
                    # 'name': self.name,
                    'partner_type': 'supplier',
                    'payment_reference': rec.payment_reference,
                    'journal_id': rec.journal_id.id,
                    'payment_type': rec.payment_type,
                    'partner_id': rec.partner_id.id,
                    'amount': rec.amount,
                    'currency_id': rec.currency_id.id,
                    'bank_reference': rec.bank_reference,
                    'cheque_reference': rec.cheque_reference,
                    'effective_date': rec.effective_date,
                    'communication': rec.ref,
                    'invoice_reference': rec.invoice_reference,
                    'payment_date': rec.date,
                    'payment_id': rec.id,
                    'company_id': rec.company_id.id,
                    'check_amount_in_words': rec.check_amount_in_words,
                    'state': 'registered',
                })
            # else:
            #     raise ValidationError(
            #         _('Alert !!  Mr.%s - You cannot create PDC Draft Payment with Zero Value '
            #           'Please Check it.') % rec.user_id.name)

    def action_post(self):
        self.create_pdc_check_payment_status()
        result = super(AccountPayment, self).action_post()

    def print_checks(self):
        """ Check that the recordset is valid, set the payments state to
        sent and call print_checks() """
        # Since this method can be called via a client_action_multi, we
        # need to make sure the received records are what we expect
        self = self.filtered(lambda r:
                             r.payment_method_id.code
                             in ['check_printing', 'pdc']
                             and r.state != 'reconciled')
        if len(self) == 0:
            raise UserError(_(
                "Payments to print as a checks must have 'Check' "
                "or 'PDC' selected as payment method and "
                "not have already been reconciled"))
        if any(payment.journal_id != self[0].journal_id for payment in self):
            raise UserError(_(
                "In order to print multiple checks at once, they "
                "must belong to the same bank journal."))

        if not self[0].journal_id.check_manual_sequencing:
            # The wizard asks for the number printed on the first
            # pre-printed check so payments are attributed the
            # number of the check the'll be printed on.
            last_printed_check = self.search([
                ('journal_id', '=', self[0].journal_id.id),
                ('check_number', '!=', "0")], order="check_number desc",
                limit=1)
            next_check_number = last_printed_check and int(
                last_printed_check.check_number) + 1 or 1
            return {
                'name': _('Print Pre-numbered Checks'),
                'type': 'ir.actions.act_window',
                'res_model': 'print.prenumbered.checks',
                'view_mode': 'form',
                'target': 'new',
                'context': {
                    'payment_ids': self.ids,
                    'default_next_check_number': next_check_number,
                }
            }
        else:
            self.filtered(lambda r: r.state == 'draft').post()
            self.write({'state': 'sent'})
            return self.do_print_checks()

    def _prepare_payment_moves(self):
        """ supered function to set effective date """
        res = super(AccountPayment, self)._prepare_payment_moves()
        inbound_pdc_id = self.env.ref(
            'base_accounting_kit.account_payment_method_pdc_in').id
        outbound_pdc_id = self.env.ref(
            'base_accounting_kit.account_payment_method_pdc_out').id
        if self.payment_method_id.id == inbound_pdc_id or \
                self.payment_method_id.id == outbound_pdc_id \
                and self.effective_date:
            res[0]['date'] = self.effective_date
            for line in res[0]['line_ids']:
                line[2]['date_maturity'] = self.effective_date
        return res


class AccountPaymentMethod(models.Model):
    _inherit = "account.payment.method"

    @api.model
    def _get_payment_method_information(self):
        res = super()._get_payment_method_information()
        res['pdc'] = {'mode': 'multi', 'domain': [('type', '=', 'bank')]}
        return res


class AccountJournal(models.Model):
    _inherit = 'account.journal'

    payment_debit_account_id = fields.Many2one('account.account', string='Default Debit Account')
    payment_credit_account_id = fields.Many2one('account.account', string='Default Credit Account')
